# /path/to/project/.cargo/config.toml
[target.aarch64-apple-darwin]
rustflags = [
  # Nightly
  "-Zshare-generics=y",
  "-Zthreads=0",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
  # Mold linker
  #
  # You may need to install it:
  #
  # - Ubuntu: `sudo apt-get install mold clang`
  # - Fedora: `sudo dnf install mold clang`
  # - Arch: `sudo pacman -S mold clang`
  # "-Clink-arg=-fuse-ld=mold",

  # Nightly
  "-Zshare-generics=y",
  "-Zthreads=0",
]
# Some systems may experience linker performance issues when running doc tests.
# See https://github.com/bevyengine/bevy/issues/12207 for details.
rustdocflags = [
  # Mold linker
  # "-Clink-arg=-fuse-ld=mold",
]
